export enum WordListTypes {
  ACTION_ERROR = 'WORDLIST_ACTION_ERROR',
  ACTION_START = 'WORDLIST_ACTION_START',
  SAVE_LIST = 'WORDLIST_SAVE_LIST',
  GET_LISTS = 'WORDLIST_GET_LISTS',
  GET_LIST = 'WORDLIST_GET_LIST',
  DELETE_LIST = 'WORDLIST_DELETE_LIST'
}
