export enum SearchTypes {
  ACTION_ERROR = 'SEARCH_ACTION_ERROR',
  ACTION_START = 'SEARCH_ACTION_START',
  SEARCH_WORD = 'SEARCH_WORD',
  SEARCH_IMAGE = 'SEARCH_IMAGE',
  SEARCH_RESET = 'SEARCH_RESET'
}
